apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui-svc
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  ports:
    - port: {{ .Values.config.rabbitMq.guiPort }}
      targetPort: {{ .Values.config.rabbitMq.guiPort }}
