server:
  port: 8085

logging:
  level:
    org.springframework.data.mongodb.core.MontoTemplate: INFO
    ROOT: INFO
    com.pwit: INFO
    jdk.eventsecurity: INFO

spring:
  profiles:
    active: dev
    include:
      - swagger
  application:
    name: messages-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URL}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: admin
    password: password

keycloak:
  enabled: true
  realm: master
  resource: messages-service
  principal-attribute: preferred_username
  bearer-only: true
  ssl-required: external
  auth-server-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/auth
