apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Chart.Name }}-svc
  name: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
    - port: {{ .Values.config.sonarqube.port }}
      targetPort: {{ .Values.config.sonarqube.port }}
      nodePort: {{ .Values.config.sonarqube.nodePort }}
  selector:
    name: {{ .Chart.Name }}
