apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.profile.authService.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: keycloak
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        args:
        - "-b"
        - "0.0.0.0"
        - "-Djboss.http.port=8081"
        - "-Dkeycloak.migration.action=import"
        - "-Dkeycloak.migration.provider=dir"
        - "-Dkeycloak.migration.dir=/config"
        - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
        - "-Dkeycloak.profile.feature.account_api=enabled"
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-cm
        ports:
        - containerPort: {{ .Values.config.authService.port }}
        # TODO - Fix readiness probe
        #readinessProbe:
        #  httpGet:
        #    path: /auth
        #    port: {{ .Values.config.authService.port }}
        #  timeoutSeconds: {{ .Values.healthCheck.authService.readinessProbe.timeoutSeconds }}
        # initialDelaySeconds: {{ .Values.healthCheck.authService.readinessProbe.initialDelaySeconds }}
        #  periodSeconds: {{ .Values.healthCheck.authService.readinessProbe.periodSeconds }}
        #  failureThreshold: {{ .Values.healthCheck.authService.readinessProbe.failureThreshold }}
        #livenessProbe:
        #  httpGet:
        #    path: /auth
        #    port: {{ .Values.config.authService.port }}
        #  timeoutSeconds: {{ .Values.healthCheck.authService.readinessProbe.timeoutSeconds }}
        #  initialDelaySeconds: {{ .Values.healthCheck.authService.readinessProbe.initialDelaySeconds }}
        #  periodSeconds: {{ .Values.healthCheck.authService.readinessProbe.periodSeconds }}
        #  failureThreshold: {{ .Values.healthCheck.authService.readinessProbe.failureThreshold }}