server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8444

logging:
  level:
    org.springframework.data.mongodb.core.MontoTemplate: INFO
    ROOT: INFO
    com.pwit: INFO
    jdk.eventsecurity: INFO
    com.pwit.appointmentsservice.feign.accountservice: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  application:
    name: appointments-service
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URL}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

openvidu:
  url: https://${MINIKUBE_IP}/openvidu-api/
  secret: YOUR_SECRET

keycloak:
  enabled: true
  realm: master
  resource: appointments-service
  principal-attribute: preferred_username
  bearer-only: true
  ssl-required: external
  auth-server-url: https://${MINIKUBE_IP}/auth
  disable-trust-manager: true

file:
  upload-dir: ./files