server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8444

logging:
  level:
    org.springframework.data.mongodb.core.MontoTemplate: INFO
    ROOT: INFO
    com.pwit: INFO
    jdk.eventsecurity: INFO

spring:
  profiles:
    active: dev
    include:
      - swagger
  application:
    name: appointments-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

openvidu:
  url: https://www.docwire.test/openvidu-api/
  secret: YOUR_SECRET

keycloak:
  enabled: true
  realm: master
  resource: appointments-service
  principal-attribute: preferred_username
  bearer-only: true
  ssl-required: external
  auth-server-url: https://docwire.test/auth
