apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/appointments/$2
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.config.appointmentsService.hostname }}-svc
          servicePort: {{ .Values.config.appointmentsService.port }}
        path: /api/appointments(/|$)(.*)
