image:
  name: appointments-service

profile:
  appointmentsService:
    logging:
      level: INFO

healthCheck:
  appointmentsService:
    readinessProbe:
      timeoutSeconds: 5
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 5
    livenessProbe:
      timeoutSeconds: 5
      initialDelaySeconds: 180
      failureThreshold: 5
      periodSeconds: 5
