apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3000'
spec:
  selector: 
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.config.grafana.port }}
      targetPort: {{ .Values.config.grafana.port }}
      nodePort: {{ .Values.config.grafana.nodePort }}
  type: NodePort
