version: "3.7"

services:
    frontend:
        image: freq/frontend:v1
        container_name: frontend
        restart: always
        ports:
          - "9040:9040"
        networks:
          - docwire_network

    account-service:
        image: freq/account-service:v1
        container_name: account-service
        ports:
            - "8083:8083"
        depends_on:
            - mongodb
        environment:
            - SPRING_DATA_MONGODB_HOST=mongodb
            - SPRING_DATA_MONGODB_PORT=27020
            - SPRING_DATA_MONGODB_DATABASE=account_service_db
            - "SPRING_PROFILES_ACTIVE=dev,swagger,dev-cal"
        networks:
            - docwire_network

    mongodb:
        image: mongo:4.2
        container_name: account-service-db
        command: mongod --port 27020
        ports:
            - "27020:27020"
        networks:
            - docwire_network
    
    rabbitmq:
        image: 'rabbitmq:3.6-management-alpine'
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - '5672:5672' # The standard AMQP protocol port
            - '15672:15672' # HTTP management UI
        networks:
            - docwire_network

networks:
    docwire_network: