apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc-dev
spec:
  selector: 
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.config.appointmentsDb.port }}
      targetPort: {{ .Values.config.appointmentsDb.port }}
      nodePort: {{ .Values.config.appointmentsDb.nodePort }}
  type: NodePort
