apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-secret
                  key: password
            - name: POSTGRES_USER
              value: sonar
          ports:
            - containerPort: {{ .Values.config.sonarqubeDb.port }}
          volumeMounts:
            # This name must match the volumes.name below.
            - name: {{ .Chart.Name }}-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: {{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
