kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
