apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Chart.Name }}-svc
  name: {{ .Chart.Name }}-svc
spec:
  ports:
    - port: {{ .Values.config.sonarqubeDb.port }}
      targetPort: {{ .Values.config.sonarqubeDb.port }}
  selector:
    name: {{ .Chart.Name }}
