apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics
      prometheus.io/port: '9090'
spec:
  selector: 
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.config.prometheus.port }}
      targetPort: {{ .Values.config.prometheus.port }}
      nodePort: {{ .Values.config.prometheus.nodePort }}
  type: NodePort
