image:
  name: messages-service

profile:
  messagesService:
    logging:
      level: INFO

healthCheck:
  messagesService:
    readinessProbe:
      timeoutSeconds: 5
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 5
    livenessProbe:
      timeoutSeconds: 5
      initialDelaySeconds: 180
      failureThreshold: 5
      periodSeconds: 5

path:
  cert: /opt/securitymanager/ssl
