apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.config.openviduServer.hostname }}-svc
          servicePort: {{ .Values.config.openviduServer.port }}
        path: /(/|$)(.*)
      - backend:
          serviceName: {{ .Values.config.openviduServer.hostname }}-svc
          servicePort: {{ .Values.config.openviduServer.port }}
        path: /openvidu-api/(/|$)(.*)
