image:
  registry: freq
  pullPolicy: IfNotPresent
  tag: v1

config:
  frontend:
    hostname: frontend
    port: 9040
  authDb:
    hostname: auth-db
    port: 5432
  authService:
    hostname: auth-service
    port: 8081
  accountService:
    hostname: account-service
    port: 8080
  accountDb:
    hostname: account-db
    port: 27020

securityContext:
  user:
    runAsUser: 985
    fsGroup: 985
    runAsNonRoot: true
