image:
  registry: freq
  pullPolicy: IfNotPresent
  tag: v1

config:
  frontend:
    hostname: frontend
    port: 9040
  authDb:
    hostname: auth-db
    port: 5432
  authService:
    hostname: auth-service
    port: 8081
  accountService:
    hostname: account-service
    port: 8445
  accountDb:
    hostname: account-db
    port: 27017
    nodePort: 32001
  messagesService:
    hostname: messages-service
    port: 8446
  messagesDb:
    hostname: messages-db
    port: 27017
  appointmentsService:
    hostname: appointments-service
    port: 8444
  appointmentsDb:
    hostname: appointments-db
    port: 27017
    nodePort: 32002
  paymentService:
    hostname: payment-service
    port: 8447
    nodePort: 32004
  paymentDb:
    hostname: payment-db
    port: 27017
    nodePort: 32003
  notificationsService:
    hostname: notifications-service
    port: 8448
  notificationsDb:
    hostname: notifications-db
    port: 27017
  rabbitMq:
    hostname: rabbit-mq
    port: 5672
    stompPort: 61613
    guiPort: 15672
  openviduServer:
    hostname: openvidu-server
    port: 4443
  openviduCoturn:
    hostname: openvidu-coturn
    port: 3478
  openviduRedis:
    hostname: openvidu-redis
    port: 6379
  prometheus:
    hostname: prometheus
    port: 9090
    nodePort: 32000
  grafana:
    hostname: grafana
    port: 3000
    nodePort: 31000
  sonarqube:
    hostname: sonarqube
    port: 9000
    nodePort: 31500
  sonarqubeDb:
    hostname: sonarqube-db
    port: 5432

securityContext:
  user:
    runAsUser: 985
    fsGroup: 985
    runAsNonRoot: true

dns:
  domain: .svc.cluster.local
  policy: ClusterFirst

globalIssuer:
  name: tsl-ca-issuer
  kind: ClusterIssuer
  secretName: my-ca-tls-secret

services:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: https
      cert-manager.io/cluster-issuer: "tls-ca-issuer"

