export default [
  {
    id: 1,
    bodyPart: 'Head',
    symptoms: [
      'Nose pain',
      'Swollen nose',
      'Runny nose',
      'Stuffy nose',
      'Headache',
      'Facial pain',
      'Fever',
      'Face swelling',
      'Face numbness',
      'Facial muscle weakness',
      'Eye pain',
      'Bloodshot eye',
      'Watery eyes',
      'Itching of eyes',
      'Earache',
      'Decreased hearing',
      'Clogged ear',
      'Itching in ear',
      'Ringing in ear',
      'Dry mouth',
      'Bad breath',
      'Gum pain',
      'Tootache',
      'Burning tounge',
    ],
  },
  {
    id: 2,
    bodyPart: 'Left shoulder',
    symptoms: [
      'Pain in upper limb',
      'Shoulder pain',
      'Shoulder pain while moving',
      'Restricted range of join motion',
      'Pain in both upper limbs',
      'Shoulder sweeling',
      'Loss of feeling in both arms',
    ],
  },
  {
    id: 3,
    bodyPart: 'Left arm',
    symptoms: [
      'Pain in upper limb',
      'Forearm pain',
      'Elbow swelling',
      'Swelling of the upper limb',
      'Wrist pain',
      'Elbow pain',
      'Wrist drop',
      'Loss of feeling in both arms',
    ],
  },
  {
    id: 4,
    bodyPart: 'Right shoulder',
    symptoms: [
      'Pain in upper limb',
      'Shoulder pain',
      'Shoulder pain while moving',
      'Restricted range of join motion',
      'Pain in both upper limbs',
      'Shoulder sweeling',
      'Loss of feeling in both arms',
    ],
  },
  {
    id: 5,
    bodyPart: 'Right arm',
    symptoms: [
      'Pain in upper limb',
      'Forearm pain',
      'Elbow swelling',
      'Swelling of the upper limb',
      'Wrist pain',
      'Elbow pain',
      'Wrist drop',
      'Loss of feeling in both arms',
    ],
  },
  {
    id: 6,
    bodyPart: 'Left hand',
    symptoms: [
      'Wrist pain',
      'One pinger pain',
      'Hand sweeling',
      'Pain of the sking around the nail',
      'Pain in fingers or hand',
      'Finger swelling',
      'Red hand',
      'Tingling fingers',
      'Trembling of one hand',
      'Loss of muscles in hands',
      'Cold hands or fingers',
    ],
  },
  {
    id: 7,
    bodyPart: 'Right hand',
    symptoms: [
      'Wrist pain',
      'One pinger pain',
      'Hand sweeling',
      'Pain of the sking around the nail',
      'Pain in fingers or hand',
      'Finger swelling',
      'Red hand',
      'Tingling fingers',
      'Trembling of one hand',
      'Loss of muscles in hands',
      'Cold hands or fingers',
    ],
  },
  {
    id: 8,
    bodyPart: 'Chest',
    symptoms: [
      'Chest pain',
      'Heartburn',
      'Fast heartbeat',
      'Palpitations',
      'Pressing chest pain',
      'Cough',
      'Accelerated breathing',
      'Shallow breathing',
      'Shortness of breath',
      'Gynecomastia',
      'Chest injury',
    ],
  },
  {
    id: 9,
    bodyPart: 'Stomach',
    symptoms: [
      'Stomach pain',
      'Colic stomach pain',
      'Burning of gnawing stomach pain',
      'Upper left side stomach pain',
      'Upper right side stomach pain',
      'Heartburn',
      'Bloating',
      'Increased abdominal size',
      'Lump in abdomen',
      'Vomiting',
      'Indegestion',
      'Diarrhea',
    ],
  },
  {
    id: 10,
    bodyPart: 'Left leg',
    symptoms: [
      'Thigh pain',
      'Join pain, hip',
      'Pain in both lower limbs',
      'Severe pain in lower limb',
      'Limping due to pain',
      'Tender leg',
      'Swollen leg',
      'Hip swelling',
      'Calf pain',
    ],
  },
  {
    id: 11,
    bodyPart: 'Right leg',
    symptoms: [
      'Thigh pain',
      'Join pain, hip',
      'Pain in both lower limbs',
      'Severe pain in lower limb',
      'Limping due to pain',
      'Tender leg',
      'Swollen leg',
      'Hip swelling',
      'Calf pain',
    ],
  },
  {
    id: 12,
    bodyPart: 'Left foot',
    symptoms: [
      'Foot pain',
      'Toe pain',
      'Sore nail',
      'Ankle pain',
      'Big toe pain',
      'Pain of the sking around the nail',
      'Swollen feet',
      'Enlarged finger tips',
    ],
  },
  {
    id: 13,
    bodyPart: 'Right foot',
    symptoms: [
      'Foot pain',
      'Toe pain',
      'Sore nail',
      'Ankle pain',
      'Big toe pain',
      'Pain of the sking around the nail',
      'Swollen feet',
      'Enlarged finger tips',
    ],
  },
];
