apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.config.paymentDb.port }}
      targetPort: {{ .Values.config.paymentDb.port }}