apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  {{- range $key, $value := .Values.services.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /api/chat/$2
  name: {{ .Chart.Name }}-ingress
spec:
  tls:
  - secretName: {{ .Chart.Name }}-tls
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.config.messagesService.hostname }}-svc
          servicePort: {{ .Values.config.messagesService.port }}
        path: /api/chat(/|$)(.*)
