apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  truststore.password: {{ b64enc .Values.credentials.encryption.truststorePassword }}
  keystore.password: {{ b64enc .Values.credentials.encryption.keystorePassword }}
  key.password: {{ b64enc .Values.credentials.encryption.keystorePassword }}