apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.profile.openviduRedis.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-cm
        ports:
        - containerPort: {{ .Values.config.openviduRedis.port }}
