apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  labels:
    type: local
    app: {{ .Chart.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete