apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.config.authDb.port }}
    targetPort: {{ .Values.config.authDb.port }}
  selector:
    app: {{ .Chart.Name }}
